### ISSUE TITLE
NOCS map

### ISSUE THREAD

**Issue by colin-de** [Leeiieeo/AG-Pose#12]
Dear author, thanks for your great work that can have a very accurate NOCS key point; I wonder how we can make use of the NOCS key point map, e.g., Can we also get the 2D-pixel coordinate of the NOCS key point to have 2D-3D correspondence? Thanks!

**Comment by Leeiieeo** [comment]
Hi, thank you for your attention to our work. 

Since our method performs keypoint detection in 3D points, AG-Pose naturally outputs 3D-3D correspondences between camera space and NOCS. 

If you want to obtain the 2D pixel coordinates of these keypoints, you can probably achieve so by using the camera intrinsic or by weighted suming other pixel coordinates based on the keypoint heatmap.

However, the current research trend seems to be moving towards better feature extraction (dino, AG-Pose, SecondPose) and network architectures (diffusion model, GenPose) and directly predict the final pose, rather than relying on intermediate correspondences.

Feel free to have more conversation if you want.
